spring:
  flyway:
    out-of-order: true
  freemarker:
    template-loader-path: "classpath:/templates"
    suffix: ".ftl"
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/pnu_feedback}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:root}
  security.user:
    name: ${ADMIN_USERNAME:admin}
    password: ${ADMIN_PASSWORD:admin}
  activemq:
    in-memory: true
jwt:
  secret: ${JWT_SECRET:secret}
app:
  baseUrl: ${APP_BASE_URL:http://localhost:8080}